language: python
cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/pre-commit
services:
  - docker
env:
  global:
    - CONTAINER: zorya-web
    - APPLICATION_NAME: zorya
before_install:
  - cp ${APPLICATION_NAME}/config.py.example ${APPLICATION_NAME}/config.py
  - echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
  - docker-compose up -d
install:
  - pip install pre-commit && pre-commit install
  - echo "${CONTAINER}:${DJANGO_PORT}"
  - ./wait-for-it.sh ${CONTAINER}:${DJANGO_PORT} -- docker-compose exec $CONTAINER pip install coverage
script:
  - pre-commit run --all-files --show-diff-on-failure
  - docker-compose exec ${CONTAINER} coverage run manage.py test
after_script:
  - docker-compose exec ${CONTAINER} coverage report --omit=*/migrations/* -m
