version: '3'

services:
  zorya-db:
    image: postgres:14.4
    environment:
      - POSTGRES_USER=postgres  # name of the application database user
      - POSTGRES_PASSWORD=postgres  # name of the application database user
      - POSTGRES_DB=postgres  # name of the application database
    volumes:
      - zoryadb:/var/lib/postgresql/data/
  zorya-web:
    build: .
    entrypoint: /code/entrypoint.sh
    environment:
      - APPLICATION_PORT=${APPLICATION_PORT:-8011}
    volumes:
      - .:/code
    ports:
      - "${APPLICATION_PORT:-8011}:${APPLICATION_PORT:-8011}"
    depends_on:
      - zorya-db

volumes:
  zoryadb:
