version: '3'

services:
  zorya-db:
    image: postgres:10.4
    volumes:
      - zoryadb:/var/lib/postgresql/data/
  zorya-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8011:8011"
    depends_on:
      - zorya-db

volumes:
  zoryadb:
