version: '3'

services:
  zorya-db:
    image: postgres:10.4
    volumes:
      - dbvolume:/var/lib/postgresql/data/
  zorya-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  zoryadb:
