# Generated by Django 2.2.8 on 2020-03-19 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='end_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='bag_path',
            field=models.CharField(default='Default bag path', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bag',
            name='origin',
            field=models.CharField(blank=True, choices=[('legacy_digital', 'Legacy Digital Processing'), ('digitization', 'Digitization')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='rights_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
