# Generated by Django 2.2.8 on 2020-04-20 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0002_auto_20200319_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='rights_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
