# Generated by Django 2.2.8 on 2020-05-11 21:06

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0003_bag_rights_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='rights_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
