# Generated by Django 2.2.10 on 2020-06-18 21:05

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0004_auto_20200511_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='rights_id',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
