# Generated by Django 2.2.10 on 2020-07-15 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0005_auto_20200618_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='start_date',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
