# Generated by Django 3.2.4 on 2021-06-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0006_bag_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='rights_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bag',
            name='rights_id',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
