# Generated by Django 4.2.19 on 2025-02-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0009_alter_bag_process_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bag',
            name='process_status',
            field=models.IntegerField(choices=[(1, 'Discovered'), (2, 'Assigned rights'), (3, 'Packaged'), (4, 'Delivered'), (5, 'Archived'), (11, 'Assigning rights'), (12, 'Creating package'), (13, 'Delivering'), (14, 'Creating archive'), (15, 'Downloaded object from S3'), (16, 'Discovering'), (17, 'Saved to database'), (18, 'Downloaded object from S3')], default=1),
        ),
    ]
