# Generated by Django 4.2.19 on 2025-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('package_bag', '0010_alter_bag_process_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bag',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
